version: '3.3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=password
      - DATABASE_HOST= db
      - DATABASE_PORT= 5432
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= password
    volumes:
      - .:/api
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  app:    
    build:      
      context: ./app     
      dockerfile: Dockerfile    
    depends_on:      
      - api    
    ports:      
      - 80:80