version: '3.3'
services:
  db:
    image: postgres
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=password
    volumes:
      - .:/api
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis